apiVersion: v1
kind: Service
metadata:
  name: my-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: frontend-web-app  # Corrected label to match the Deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80  # Matching the containerPort
