// Jenkinsfile

pipeline {
    agent any

    stages {
        stage('Run Terraform Command') {
            steps {
                echo 'Running Terraform command...'
                // Add your Terraform command here
                // sh 'terraform init'
                // sh 'terraform apply -auto-approve'
            }
        }

        stage('Run Build Command') {
            steps {
                echo 'Running build command...'
                // Add your build command here (e.g., Maven, Gradle, etc.)
                sh './build.sh'
            }
        }

        stage('Run Scan Code Command') {
            steps {
                echo 'Running code scan...'
                // Add your code scanning command here (e.g., SonarQube, etc.)
                // sh 'sonar-scanner'
            }
        }

        stage('Run Docker Command') {
            steps {
                echo 'Running Docker command...'
                // Add your Docker command here (e.g., build, run, etc.)
                // docker build -t angular-app .
                sh 'docker build -t <your-dockerhub-username>/my-web-app:latest ../docker/Dockerfile'
                // sh 'docker run myappimage -d -p 8080:80 mywebapp:v1'
                sh 'docker push <your-dockerhub-username>/my-web-app:latest'
            }
        }

        stage('Run Terraform Command Again') {
            steps {
                echo 'Running Terraform command again...'
                // Add the final Terraform command here
                // sh 'terraform plan'
                // docker run -d -p 8080:80 angular-app
            }
        }
        // stage('Run Terraform Command Again') {
        //     steps {
        //         echo 'Running docker container'
        //         RUN 'docker run -d -p 8080:80 angular-app'
        //     }
        // }
    }
}
