apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: database-web-app
  template:
    metadata:
      labels:
        app: database-web-app
    spec:
      containers:
      - name: database-web-app-container
        image: harshitaranya/harshit:databaseserver-d1
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: database-web-app-secret
              key: DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-web-app-secret
              key: DB_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: database-web-app-config
              key: DB_NAME
        - name: POSTGRES_HOST_AUTH_METHOD
          value: "scram-sha-256"  # More secure than 'trust'
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config  # Mount ConfigMap
        - name: secret-volume
          mountPath: /etc/secrets  # Mount Secret (optional)
      volumes:
      - name: config-volume
        configMap:
          name: database-web-app-config  # ConfigMap for non-sensitive data
      - name: secret-volume
        secret:
          secretName: database-web-app-secret  # Secret for sensitive data
