apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: database-web-app
  template:
    metadata:
      labels:
        app: database-web-app
    spec:
      containers:
      - name: database-web-app-container
        image: <your-dockerhub-username>/database-my-web-app:latest
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config  # Mount the ConfigMap
        - name: secret-volume
          mountPath: /etc/secrets  # Mount the Secret (DB_PASSWORD will be available here)
      volumes:
      - name: config-volume
        configMap:
          name: database-web-app-config  # ConfigMap for non-sensitive data
      - name: secret-volume
        secret:
          secretName: database-web-app-secret  # Secret for sensitive data
---
apiVersion: v1
kind: Service
metadata:
  name: database-web-app-service
spec:
  selector:
    app: database-web-app
  ports:
  - protocol: TCP
    port: 4432
    targetPort: 5432
  type: ClusterIP
