apiVersion: v1
kind: Secret
metadata:
  name: database-web-app-secret
type: Opaque
data:
  DB_PASSWORD: c2VjdXJlcGFzc3dvcmQ=  # Base64 encoded value of "securepassword"
  DB_USER: ZGJ1c2Vy  # Base64 encoded value of "dbuser" ZGJ1c2Vy | postgres cG9zdGdyZXM= | echo -n "postgres" | base64