version: '3.8'

services:
  database:
    # image: postgres:latest
    image: harshitaranya/harshitrepo:backend:v1
    container_name: mydb
    networks:
      - app_network
    volumes:
      - db_data:/var/lib/postgresql/data
    #this should be set in Jenkinsfile as variables
    # POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB, POSTGRES_HPORT, POSTGRES_CPORT
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HPORT: ${POSTGRES_HPORT}   # Host port
      POSTGRES_CPORT: ${POSTGRES_CPORT}   # Container port
    ports:
      - "${POSTGRES_HPORT}:${POSTGRES_CPORT}"  # Mapping host port to container port

networks:
  app_network:
    external: true

volumes:
  db_data:
    external: false
