version: '3.8'

services:
  backend:
    image: harshitaranya/harshitrepo:backend:v1
    container_name: backend_container
    networks:
      - app_network     
    environment:
      DB_HOST: database # localhost
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_DATABASE: simpledb
      DB_PORT: 5432

networks:
  app_network:
    external: true
