# Stage 1: Build
FROM httpd:latest

# Set working directory inside the container
# WORKDIR /app

# Copy the Maven project files to the container
COPY ../app var/www/html

# Expose the application's port (e.g., 8080)
EXPOSE 80
