apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-web-app
  template:
    metadata:
      labels:
        app: backend-web-app
    spec:
      containers:
      - name: backend-web-app-container
        image: <your-dockerhub-username>/backend-my-web-app:latest
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: backend-web-app-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: backend-web-app-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: backend-web-app-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: backend-web-app-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: backend-web-app-config
              key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: backend-web-app-service
spec:
  selector:
    app: backend-web-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
