apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-web-app-config
data:
  DB_HOST: "database-web-app-service"  # Replace with actual database host if needed
  DB_PORT: "5432"       # Replace with actual database port
  DB_NAME: "mydatabase" # Replace with actual database name
  TPORT: "3001"
  APIHOST: "backend-web-app-service"
#kubectl apply -f backend-config.yaml
